name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: werf/actions/build-and-publish@master
      env:
        WERF_LOG_VERBOSE: "on"

